# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://github.com/rubocop-hq/rubocop/blob/master/manual/configuration.md
AllCops:
  Include:
    - Cheffile
    - Gemfile
    - Rakefile
    - attributes/*
    - libraries/*
    - recipes/*
  Exclude:
   - templates/**/*
   - cookbooks/**/*
   - tmp/**/*

LineLength:
  Max: 120
