default['lyraphase_workstation']['max_for_live']['dmg']['source']      = 'http://www.lyraphase.com/doc/installers/mac/Max731_161019.dmg'
default['lyraphase_workstation']['max_for_live']['dmg']['checksum']    = 'a03ea117c8d40bbc203188d114dc22d0abe4c96281c6d5afa3e1037fa1339af1'
default['lyraphase_workstation']['max_for_live']['dmg']['volumes_dir'] = 'Max7_161017_340a77a'
default['lyraphase_workstation']['max_for_live']['dmg']['dmg_name']    = 'Max731_161019'
default['lyraphase_workstation']['max_for_live']['dmg']['app']         = 'Max'
default['lyraphase_workstation']['max_for_live']['dmg']['type']        = 'app'
# default['lyraphase_workstation']['max_for_live']['dmg']['package_id']  = 'com.cycling74.Max61.pkg'
