default['lyraphase_workstation']['polyverse_infected_mushroom_manipulator'] = {}
default['lyraphase_workstation']['polyverse_infected_mushroom_manipulator']['dmg']['source']      = 'http://www.lyraphase.com/doc/installers/mac/Infected Mushroom - Manipulator v1.01.dmg'
default['lyraphase_workstation']['polyverse_infected_mushroom_manipulator']['dmg']['checksum']    = "d1b16dfd199b6a69692f7901edc4546dbf3f43e927bc08e14c5d1c83b5798e95"
default['lyraphase_workstation']['polyverse_infected_mushroom_manipulator']['dmg']['volumes_dir'] = "Manipulator Setup"
default['lyraphase_workstation']['polyverse_infected_mushroom_manipulator']['dmg']['dmg_name']    = 'Infected Mushroom - Manipulator v1.01'
default['lyraphase_workstation']['polyverse_infected_mushroom_manipulator']['dmg']['app']         = 'Manipulator Setup'
#default['lyraphase_workstation']['polyverse_infected_mushroom_manipulator']['dmg']['package_id']  = 'com.polyversemusic.ManipulatorSetup.IWish64.pkg'
default['lyraphase_workstation']['polyverse_infected_mushroom_manipulator']['dmg']['type']        = 'pkg'
default['lyraphase_workstation']['polyverse_infected_mushroom_manipulator']['license'] = {}
default['lyraphase_workstation']['polyverse_infected_mushroom_manipulator']['license']['email']   = nil
default['lyraphase_workstation']['polyverse_infected_mushroom_manipulator']['license']['key']     = nil
