default['lyraphase_workstation']['trackspacer']['dmg']['source']      = 'http://www.lyraphase.com/doc/installers/mac/Trackspacer_V205.dmg'
default['lyraphase_workstation']['trackspacer']['dmg']['checksum']    = '58d04c49e396eda56ed1d07bf7716e4e3355bec5dabd7931208a3be4fedd2840'
default['lyraphase_workstation']['trackspacer']['dmg']['volumes_dir'] = 'Trackspacer 2.0.5 Full'
default['lyraphase_workstation']['trackspacer']['dmg']['dmg_name']    = 'Trackspacer_V205'
default['lyraphase_workstation']['trackspacer']['dmg']['app']         = 'Trackspacer_V205'
default['lyraphase_workstation']['trackspacer']['dmg']['type']        = 'mpkg'
default['lyraphase_workstation']['trackspacer']['dmg']['package_id']  = 'com.wavesfactory.pkg.trackspacer'
default['lyraphase_workstation']['trackspacer']['license'] = {}
default['lyraphase_workstation']['trackspacer']['license']['serial'] = nil
