---
name: ci

on:
  pull_request:
    branches:
      - master
      - main
      - develop
  push:
    branches:
      - master
      - main
      - develop

jobs:
  rake-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Delete Chef gem files that knife test chokes on
        run: rm -rf ./vendor/bundle/ruby/*/gems/chef-*/spec/data/client.d_02/foo.rb
      - name: Run rake ci
        run: |
          bundle exec rake ci

  integration:
    needs: [rake-ci]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #exclude:
        include:
          - os: 'macos-11'
            suite: 'default'
            KITCHEN_LOCAL_YAML: '.kitchen.exec.yml'
          - os: 'macos-12'
            suite: 'default'
            KITCHEN_LOCAL_YAML: '.kitchen.exec.yml'
      fail-fast: false

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Chef
        uses: actionshub/chef-install@main
      - name: Dokken
        uses: actionshub/test-kitchen@main
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: ${{ matrix.KITCHEN_LOCAL_YAML }}
        with:
          suite: ${{ matrix.suite }}
          os: ${{ matrix.os }}
      - name: Print debug output on failure
        if: failure()
        run: |
            set -x
            sudo journalctl -l --since today
            sudo docker version
            sudo docker info
            KITCHEN_LOCAL_YAML=${{ matrix.KITCHEN_LOCAL_YAML }} /usr/bin/kitchen exec ${{ matrix.suite }}-${{ matrix.os }} -c "journalctl -l"
